
#ifndef __BTN_ATMEGA328P_H__
#define __BTN_ATMEGA328P_H__

#define D_BTN_REG_PCINT0_PCMSK		PCMSK0
#define D_BTN_BIT_PCINT0_PCMSK		PCINT0
#define D_BTN_REG_PCINT0_PORT		PORTB
#define D_BTN_BIT_PCINT0_PORT		PB0
#define D_BTN_REG_PCINT0_DDR		DDRB
#define D_BTN_BIT_PCINT0_DDR		DDB0
#define D_BTN_REG_PCINT0_PIN		PINB
#define D_BTN_BIT_PCINT0_PIN		PINB0

#define D_BTN_REG_PCINT10_PCMSK		PCMSK1
#define D_BTN_BIT_PCINT10_PCMSK		PCINT10
#define D_BTN_REG_PCINT10_PORT		PORTC
#define D_BTN_BIT_PCINT10_PORT		PC2
#define D_BTN_REG_PCINT10_DDR		DDRC
#define D_BTN_BIT_PCINT10_DDR		DDC2
#define D_BTN_REG_PCINT10_PIN		PINC
#define D_BTN_BIT_PCINT10_PIN		PINC2

#define D_BTN_REG_PCINT11_PCMSK		PCMSK1
#define D_BTN_BIT_PCINT11_PCMSK		PCINT11
#define D_BTN_REG_PCINT11_PORT		PORTC
#define D_BTN_BIT_PCINT11_PORT		PC3
#define D_BTN_REG_PCINT11_DDR		DDRC
#define D_BTN_BIT_PCINT11_DDR		DDC3
#define D_BTN_REG_PCINT11_PIN		PINC
#define D_BTN_BIT_PCINT11_PIN		PINC3

#endif //__BTN_ATMEGA328P_H__

